DROP TABLE IF EXISTS User;
CREATE TABLE IF NOT EXISTS User
(
    id       INT AUTO_INCREMENT PRIMARY KEY,
    pseudo   VARCHAR(10)  NOT NULL,
    password VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS Car;
CREATE TABLE Car
(
    id    INT AUTO_INCREMENT PRIMARY KEY,
    brand VARCHAR(30) NOT NULL,
    model VARCHAR(30) NOT NULL,
    img   CLOB DEFAULT NULL
);

DROP TABLE IF EXISTS Comment;
CREATE TABLE IF NOT EXISTS Comment
(
    id      INT AUTO_INCREMENT PRIMARY KEY,
    car_id  INT,
    user_id Int,
    text    TEXT NOT NULL
);